on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
  
    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3    
    
    - name: Build Lib
      run: dotnet build Shatterpoint.Lib/Shatterpoint.Lib.csproj --configuration Release
      
    - name: Test Lib
      run: dotnet test Shatterpoint.Test/Shatterpoint.Test.csproj --configuration Release  
