name: Build MAUI, Run Lib Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
  
    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3    

    - name: Setup kstf
      run: |
        echo "${{ secrets.KSTF }}" > shatterpointhelper.keystore.asc
        gpg -d --passphrase "${{ secrets.GPGP }}" --batch shatterpointhelper.keystore.asc > shatterpointhelper.keystore
    
    - name: Install .NET MAUI
      run: dotnet workload install maui      
    
    - name: Build Lib
      run: dotnet build Shatterpoint.Lib/Shatterpoint.Lib.csproj -c Release
      
    - name: Test Lib
      run: dotnet test --configuration Release --no-build
      
    - name: Build MAUI
      run: dotnet build Shatterpoint.Maui/Shatterpoint.Maui.csproj -c Release -f net8.0-android /p:AndroidSigningKeyStore=shatterpointhelper.keystore /p:AndroidSigningKeyAlias=shatterpointhelper /p:AndroidSigningKeyPass="${{ secrets.KSTP }}" /p:AndroidSigningStorePass="${{ secrets.KSTPA }}" --no-restore

    - name: Upload aab and apk
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
